title: Cyril's GitHub Page
description: >-
  _config.yml 파일에 있음
baseurl: ""
url: "https://mikliryc.github.io"

markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

plugins: []

exclude:
  - Gemfile
  - Gemfile.lock
  - buildLocal.bat
  - README.md
  - my_commits.txt
  - my_commits_01.gitlog
  - my_commits_02.gitlog
  - my_commits_03.gitlog
  - "GoMap tile 최적화"
  - .git
  - .idea
  - .jekyll-cache
  - _site
  - "*.gitlog"
  - "*.ps1"
  - "temp_*.txt"
  - plan.md

